### ISSUE TITLE
前端单独部署在nginx显示空白

### ISSUE THREAD

**Issue by D32vd** [meloalright/guora#34]
nginx关键配置如下，其他都是默认值
```
server {
        listen 80;
        location / {
            root /home/yang/guora/web;
        }
    }
```
在浏览器打开后一片空白，只有favicon.ico和网页标题。经过测试，web文件夹下的每个文件都能手动请求到。
这是F12控制台报的两个错
```
RangeError: Incorrect locale information provided
    at Function.supportedLocalesOf (<anonymous>)
    at c (create-intl.js:41:33)
    at f (provider.js:90:20)
    at new e (provider.js:109:19)
    at va (react-dom.production.min.js:135:171)
    at rc (react-dom.production.min.js:175:149)
    at ql (react-dom.production.min.js:261:396)
    at Yc (react-dom.production.min.js:230:22)
    at Kc (react-dom.production.min.js:229:362)
    at Ec (react-dom.production.min.js:223:216)
```
```
create-intl.js:41  Uncaught RangeError: Incorrect locale information provided
    at Function.supportedLocalesOf (<anonymous>)
    at c (create-intl.js:41:33)
    at f (provider.js:90:20)
    at new e (provider.js:109:19)
    at va (react-dom.production.min.js:135:171)
    at rc (react-dom.production.min.js:175:149)
    at ql (react-dom.production.min.js:261:396)
    at Yc (react-dom.production.min.js:230:22)
    at Kc (react-dom.production.min.js:229:362)
    at Ec (react-dom.production.min.js:223:216)
```

**Comment by meloalright** [comment]
不能基于 nginx 提供静态页面

这个项目是依赖 go 生成页面的

主要在 internal/view 下面的逻辑中
